### ISSUE TITLE
Some modifications

### ISSUE THREAD

**Issue by fchareyron** [SIPp/pysipp#18]
Hi

I join a patch file including some needed modifications to use pysipp properly in my software.

In command.py, some missing SIPp parameters.
In agent.py and __init__.py, some modifications to handle properly the log dir and to generate error log file.
In report.py, some modifications to avoid seldom exception cases. For any reason, proc.streams.stderr doesn't exist when used.

I hope it's useful enough to be included in the product.
Regards
Frederic

[pysipp.patch.zip](https://github.com/SIPp/pysipp/files/376314/pysipp.patch.zip)

**Comment by tgoodlet** [comment]
Hey @fchareyron thanks for the work :)

Can you please open a [Pull Request](https://help.github.com/articles/using-pull-requests/) so that we can got over your changes using Github's lovely review tools.
Let me know if you run into any problems.
Thanks!
