### ISSUE TITLE
Rare premature stderr access

### ISSUE THREAD

**Issue by tgoodlet** [SIPp/pysipp#21]
@fchareyron has reported in #19 that in some cases at [report.py:51](https://github.com/SIPp/pysipp/blob/master/pysipp/report.py#L51) `proc.streams.stderr` may not exist upon attribute access. 

If this is possible we need a working example that can reproduce it.
@fchareyron please provide a script (or even better a test) that demonstrates this issue.
Thanks!

**Comment by fchareyron** [comment]
'streams'  is created by proc.communicate() in a thread created after 
popen is called. There is a short delay between the 2 function calls.

The library I am building is used for load test purposes. It creates 
multiple threads handling the same scenario with differents parameters. 
The goal is to load asterisk from multiple UAC/AUS pairs exchanging 
multiple calls at the same time.
The server that supports the library is busy, and the delay between the 
call to popen and the call to proc.communicate() may vary. If any 
exception occurs, it is possible that 'streams' is used in report.py 
before being created.
The patch creates the missing attribute where the exception is risen 
when it occurs. It is not an elegant solution, but it works. An other 
solution would be to create 'stream' just after calling popen.

**Comment by tgoodlet** [comment]
Ah now I understand. Yes there is a better solution you can use that's already built in.

You can actually run multiple scenarios asynchronously using `scenario(block=False)` which is a non blocking call such that you can launch scenarios in a batch without having to launch multiple threads on your library end. You can also collect the results and invoke the stuff in `report.py`. See the details in [`pysipp_run_protocol`](https://github.com/SIPp/pysipp/blob/master/pysipp/__init__.py#L242). To collect each scenario's results you can call `scenario.finalize()` in a loop.

This will definitely guarantee that streams exists.

**Comment by fchareyron** [comment]
I really want to implement your solution. In fact, I tried to use the 
non-blocking mode, but I did not understand how. So I gave up.

But I still do not understand how to do, is there an example of 
implementation?

**Comment by tgoodlet** [comment]
@fchareyron please take a look at the [async launching section](https://github.com/SIPp/pysipp#async-scenario-launching) of the `README`.
If it is still not clear please let me know.
