### ISSUE TITLE
xxx_file is not respected in defaults

### ISSUE THREAD

**Issue by fchareyron** [SIPp/pysipp#23]
File names provided by xxxx_file parameter are lost. For example, error_file value is lost and the error file name is always the default one.

In agent.py at line 130, the provided file name contained in attr is ignored. The fix just uses attr if provided.

        for name, attr in self.iter_logfile_items():
            setattr(
                self, name, path.join(
                    logdir or self.logdir or tempfile.gettempdir(),
                    attr or "{}_{}".format(self.name, name))
                )
        self.enable_tracing()

**Comment by tgoodlet** [comment]
@fchareyron should be working now.
Thanks for reporting.
