### ISSUE TITLE
"how to" get access to report.py ?

### ISSUE THREAD

**Issue by stadelmannj** [SIPp/pysipp#43]
Hi, 
when executing a test, I'd like to get back the result of the call. it looks like report.py can do this but I could not figure out how to use it. 
can anybody give some hints ?

**Comment by tgoodlet** [comment]
@stadelmannj when you say
>result of the call

Are you looking for the the return code?

**Comment by tgoodlet** [comment]
Actually looking at the code maybe it makes more sense to return a `dict` of `pysipp.Agent` -> `Process` from `Scenario.__call__()`?

**Comment by stadelmannj** [comment]
@tgoodlet 
can you further explain your last Response ?  Unfortunatelly, I'm really not a expert, hence struggling a bit what you mean and how to use it.

**Comment by goodboy** [comment]
@stadelmannj I'm partially confused what *output* you're looking for?
Are you looking for the return code from the SIPp command(s) or the logging output?

**Comment by goodboy** [comment]
Closing as no further clarification was provided.
