### ISSUE TITLE
how to keep uas running without an infinite loop ? 

### ISSUE THREAD

**Issue by stadelmannj** [SIPp/pysipp#44]
when launching UAS with a scen file, the process stops after the it's first iteration. 
when launching the exact same scen file via CLI, it process keeps running until manuel interuption.

is there any other option to keep the UAS scene running other then creating an infinite loop (while True:), which starts a new process after every iteration ?

**Comment by tgoodlet** [comment]
Hi @stadelmannj. One of the main purposes of `pysipp` is to be used as an automated testing tool and *not* so much as an interactive tool (which `SIPp` **is** intended to be). As such `pysipp` specifies the `-m 1` flag by default. You can always change this value per agent (or globally using the scenario instance) or remove it entirely by setting `Agent.call_count = None`.

As an example using `ipython`:

```python
In [1]: import pysipp

In [2]: s = pysipp.scenario()

In [3]: s.call_count
Out[3]: 1

In [4]: s.cmditems()
Out[4]: 
[('uas',
  "'/home/tyler//bin/sipp' -i '0.0.0.0' -p '46593' -mi '0.0.0.0' -mp '60723' -sn 'uas' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uas_log_file' -screen_file '/tmp/uas_screen_file' -trace_logs -trace_screen "),
 ('uac',
  "'/home/tyler//bin/sipp' '0.0.0.0':'46593' -i '0.0.0.0' -p '52405' -mi '0.0.0.0' -mp '41084' -sn 'uac' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_log_file' -screen_file '/tmp/uac_screen_file' -trace_logs -trace_screen ")]

In [5]: s.call_count = None

In [6]: s.cmditems()
Out[6]: 
[('uas',
  "'/home/tyler//bin/sipp' -i '0.0.0.0' -p '46593' -mi '0.0.0.0' -mp '60723' -sn 'uas' -recv_timeout '5000' -r '1' -l '1' -log_file '/tmp/uas_log_file' -screen_file '/tmp/uas_screen_file' -trace_logs -trace_screen "),
 ('uac',
  "'/home/tyler//bin/sipp' '0.0.0.0':'46593' -i '0.0.0.0' -p '52405' -mi '0.0.0.0' -mp '41084' -sn 'uac' -recv_timeout '5000' -r '1' -l '1' -log_file '/tmp/uac_log_file' -screen_file '/tmp/uac_screen_file' -trace_logs -trace_screen ")]
```

So after setting the `call_count` to `None` you won't see the `-m` flag passed to the server agent.
Hope this helps.

**Comment by tgoodlet** [comment]
@stadelmannj did this end up working for you?

**Comment by stadelmannj** [comment]
@tgoodlet 
I'm sorry but I'm still struggling. my idea was to use the pysipp.server() agent to simply launch a UAS responding to incomming invites until i shut it down. but the call_count options does not seem to work with pysipp.server.

based on your comments, i tried to use pysipp.scenarion() instead but can't even get a single call answered. from the scen.cmditems() outpout, I see all IP's are set to 0.0.0.0, hence the agent won't listen to any message.
but when i try to set use srcaddr=('192.168.2.157', 5060) as pysipp.scenarion() parameter, it's not accepted, even show dir(scen) actually shows it as valid attribute.
and if i configure it manually instead by using scen.srcaddr='192.168.2.157', it also does not work. the Server IP is still 0.0.0.0.
here's what i have so far:
```
scen = pysipp.scenario()
scen.srcaddr='192.168.2.157'
scen.call_count=None
scen.scen_file = './uas-basic-call.xml'
scen()
```

**Comment by stadelmannj** [comment]
@tgoodlet . have you had a change to look into this ? thanks Juerg

**Comment by tgoodlet** [comment]
@stadelmannj sorry I just took a look at this. It looks like the in the `scenario` case there is a bug somehow from the [`netplug.py`](https://github.com/SIPp/pysipp/blob/master/pysipp/netplug.py#L38) module. It appears the `ua.local_host` isn't being set? I'll have to look further at this.

For the `pysipp.server()` you should be able to do:
```python
In [20]: s = pysipp.server(call_count=None, srcaddr=('192.168.2.157', 5060))

In [21]: s.cmd
Out[21]: "'/home/tyler//bin/sipp' -i '192.168.2.157' -p '5060' -sn 'uas' "

In [22]: s()
stderr for 'uas' @ ('192.168.2.157', 5060)
b'2018-12-11\t20:55:33.504485\t1544579733.504485: Unable to bind main socket, errno = 99 (Cannot assign requested address).\n'

'screen_file' contents for 'uas' @ ('192.168.2.157', 5060):
```
Obviously the error there is because that isn't my IP.

**Comment by tgoodlet** [comment]
Figured it out. You have to use this syntax:
```python
scen = pysipp.scenario(defaults={'srcaddr':('192.168.2.157', 5060), 'call_count': None, 'scen_file': './uas-basic-call.xml'})
scen.cmditems()
[('uas',
  "'/home/tyler//bin/sipp' -i '192.168.2.157' -p '5060' -mp '60520' -sn 'uas' -sf './uas-basic-call.xml' -recv_timeout '5000' -r '1' -l '1' -log_file '/tmp/uas_log_file' -screen_file '/tmp/uas_screen_file' -trace_logs -trace_screen "),
 ('uac',
  "'/home/tyler//bin/sipp' -i '192.168.2.157' -p '5060' -mp '51850' -sn 'uac' -sf './uas-basic-call.xml' -recv_timeout '5000' -r '1' -l '1' -log_file '/tmp/uac_log_file' -screen_file '/tmp/uac_screen_file' -trace_logs -trace_screen '192.168.2.157':'5060'")]
```
Like I mentioned before the way to figure out why stuff isn't getting set they way you'd expect is to enable logging:
```python
from pysipp.utils import log_to_stderr
log_to_stderr("DEBUG")
#.. run your code ...
```

**Comment by goodboy** [comment]
ping @stadelmannj can this be closed or is there still an open issue?

**Comment by stadelmannj** [comment]
@goodboy . Yes, this can be closed. Sorry i missed to respond. Many thanks for your help.
