### ISSUE TITLE
Error "Missing remote host parameter. This scenario requires it.\n' "

### ISSUE THREAD

**Issue by access2praveen** [SIPp/pysipp#45]
I am encountering below error when i am trying to run sipp scenario file through pysipp 

`root@voiceqa-desktop:/opt/test# python3 sipp.py
('10.204.66.84', 5080)
stderr for 'uac_AMR_BW' @ ('0.0.0.0', 34607)
b'2018-10-08\t16:31:39.337407\t1538976699.337407: Missing remote host parameter. This scenario requires it.\n
'screen_file' contents for 'uac_AMR_BW' @ ('0.0.0.0', 34607):
Traceback (most recent call last):
  File "sipp.py", line 8, in <module>
    scen()
  File "/usr/local/lib/python3.5/dist-packages/pysipp/agent.py", line 413, in __call__
    raise_exc=raise_exc, **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.5/dist-packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/pysipp/__init__.py", line 250, in pysipp_run_protocol
    finalize(cmds2procs, raise_exc=raise_exc)
  File "/usr/local/lib/python3.5/dist-packages/pysipp/__init__.py", line 228, in finalize
    raise SIPpFailure(msg)
pysipp.SIPpFailure: Some agents failed
'uac_AMR_BW' with exit code 255 -> Command or syntax error: check stderr output
`

My Directory has only one scenario file 

`root@voiceqa-desktop:/opt/test# ls /home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/           

                   uac_40sec_harvard.amr  uac_AMR_BW.xml  uac_Harvard_AMR.amr`

My python script looks as below 

`import pysipp
uas = pysipp.server(srcaddr=('10.204.66.84', 5080))
print(uas.srcaddr)
uac = pysipp.client(destaddr=uas.srcaddr)
#scen = pysipp.scenario()
scen = pysipp.scenario(dirpath='/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB',proxyaddr=('10.204.66.84', 5080))
#print(scen.cmditems())
scen()
pysipp.log_to_stderr('DEBUG')
`

Kindly let me know how to fix this 

Thanks
Praveen

**Comment by access2praveen** [comment]
I have tried with latest version of pysipp  as well , but it didnt resolve my problem , can you please help me how to iterate over scenario files , I have managed to run one instance of sipp with single scenario file with below code


`import pysipp uas = pysipp.server(srcaddr=('10.204.66.84', 5080)) print(uas.srcaddr) uac = pysipp.client(destaddr=uas.srcaddr) #scen = pysipp.scenario() scen = pysipp.scenario(dirpath='/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB',proxyaddr=('10.204.66.84', 5080)) #print(scen.cmditems()) scen() pysipp.log_to_stderr('DEBUG')`

**Comment by goodboy** [comment]
ping @access2praveen did this end up solving your issue. Trying to get in fixes for an alpha release as per #42!

**Comment by goodboy** [comment]
Got no feedback on this so closing for now.
