### ISSUE TITLE
set -t t1 (tcp flag)

### ISSUE THREAD

**Issue by DanielBryars** [SIPp/pysipp#58]
Hello,

Please can you tell me how I can pass the -t parameter to SIPP?

Thanks,

Daniel

**Comment by DanielBryars** [comment]
Read the code :)

`uac = pysipp.client(destaddr=('srs', 5060), transport='t1')`

**Comment by goodboy** [comment]
@DanielBryars if it's not documented well enough feel free to pr it in 🙂
