### ISSUE TITLE
Pluggy version 1.0.0 breaks pysipp

### ISSUE THREAD

**Issue by kontsaki** [SIPp/pysipp#74]
```
conftest.py:3: in <module>
    import pysipp
/usr/local/lib/python3.9/dist-packages/pysipp/__init__.py:23: in <module>
    from . import launch, report, plugin, netplug, agent
/usr/local/lib/python3.9/dist-packages/pysipp/plugin.py:9: in <module>
    mng = pluggy.PluginManager('pysipp', implprefix='pysipp')
E   TypeError: __init__() got an unexpected keyword argument 'implprefix'
```

https://pluggy.readthedocs.io/en/latest/changelog.html#deprecations-and-removals

**Comment by goodboy** [comment]
Oof.

I guess we need to port then and [pin to](https://github.com/SIPp/pysipp/blob/master/setup.py#L39) pre-1.0.

Any PR takers 😉

**Comment by Enkumicahel** [comment]
Hello,
Any solutions for this one? I am stuck here.

**Comment by goodboy** [comment]
I mean I can probably do this but I don't really have the bandwidth atm.
We kinda need some new conribs to step up and take the reigns.

**Comment by goodboy** [comment]
Ahh yeah so I think all that needs to be done is drop the `kwarg` [from here](https://github.com/SIPp/pysipp/blob/master/pysipp/plugin.py#L9).

I'm not entirely sure if that'll fix it but i'm pretty sure we're already using `HookimplMarker` so it's just a matter of removing that one bit I think.

**Comment by Enkumicahel** [comment]
I am hoping to be one of your contribs. Just got to step over this hurdle first thing. Thanks for this great repo. Hope more of us can participate.

**Comment by davemcbride** [comment]
> Hello, Any solutions for this one? I am stuck here.

I'm no expert but installing the old version of pluggy worked for me:

`pip install 'pluggy==0.11.0' --force-reinstall`

**Comment by goodboy** [comment]
I'm pretty sure this is a super easy fix y'all.

Please someone give it a try 😉

**Comment by Enkumicahel** [comment]
I have tried @davemcbride suggestion and it worked for me. I honestly didn't understand what @goodboy suggested. Anyways, thanks, guys. Cheers!

**Comment by goodboy** [comment]
> I have tried @davemcbride suggestion and it worked for me. 

So is anyone going to PR this in then 😂 

> I honestly didn't understand what @goodboy suggested. Anyways, thanks, guys. Cheers!

You would make a patch like this:

```
diff --git a/pysipp/plugin.py b/pysipp/plugin.py
index cd88b92..23ce90a 100644
--- a/pysipp/plugin.py
+++ b/pysipp/plugin.py
@@ -6,7 +6,7 @@ import contextlib
 from . import hookspec

 hookimpl = pluggy.HookimplMarker("pysipp")
-mng = pluggy.PluginManager("pysipp", implprefix="pysipp")
+mng = pluggy.PluginManager("pysipp")
 mng.add_hookspecs(hookspec)
 ```
 
 After this patch there's no more issue on `import pysipp`..like i said.

**Comment by goodboy** [comment]
Now the question is whether y'all want to pin to pluggy 1.0 +
