### ISSUE TITLE
Passing additional arguments to SIPP.

### ISSUE THREAD

**Issue by afrolov-fuze** [SIPp/pysipp#75]
Hi, thanks for the great software! I have one question though, could not find the answer in the docs or code:
How can I pass arguments that are not listed in `pysipp.command.sipp_spec`, like -`min_rtp_port`, to SIPP executable?

**Comment by goodboy** [comment]
@afrolov-fuze good question 😂 

I'm not sure we have a way to do that easily.

If you have ideas for how you'd like it exposed please do speak up.

**Comment by iikercosta** [comment]
> @afrolov-fuze good question 😂
> 
> I'm not sure we have a way to do that easily.
> 
> If you have ideas for how you'd like it exposed please do speak up.

The way to support more arguments easily could be by modifying the sipp_spec list in the commands module. As for example in this PR: https://github.com/SIPp/pysipp/pull/82
